### ISSUE TITLE
Add Folia 1.21.4 Support

### ISSUE THREAD

**Issue by Tudorhc5** [qixils/minecraft-crowdcontrol#209]
Please update to include support for Folia 1.21.4

Tried loading the latest version, 3.6.2-Paper, on a folia 1.21.4 server, and I encounter the following error:

```
[13:57:30 INFO]: [CrowdControl] Enabling CrowdControl v3.6.2+paper
[13:57:30 ERROR]: Error occurred while enabling CrowdControl v3.6.2+paper (Is it up to date?)
java.lang.NoSuchFieldError: Class org.bukkit.attribute.Attribute does not have member field 'org.bukkit.attribute.Attribute GENERIC_MAX_HEALTH'
        at CrowdControl-Paper-3.6.2.jar/dev.qixils.crowdcontrol.plugin.paper.commands.LootboxCommand.<clinit>(LootboxCommand.java:55) ~[CrowdControl-Paper-3.6.2.jar:?]
        at CrowdControl-Paper-3.6.2.jar/dev.qixils.crowdcontrol.plugin.paper.CommandRegister.lambda$createCommands$6(CommandRegister.java:40) ~[CrowdControl-Paper-3.6.2.jar:?]
        at CrowdControl-Paper-3.6.2.jar/dev.qixils.crowdcontrol.common.command.AbstractCommandRegister.init(AbstractCommandRegister.java:49) ~[CrowdControl-Paper-3.6.2.jar:?]
        at CrowdControl-Paper-3.6.2.jar/dev.qixils.crowdcontrol.common.command.AbstractCommandRegister.initTo(AbstractCommandRegister.java:71) ~[CrowdControl-Paper-3.6.2.jar:?]
        at CrowdControl-Paper-3.6.2.jar/dev.qixils.crowdcontrol.common.command.AbstractCommandRegister.initTo(AbstractCommandRegister.java:77) ~[CrowdControl-Paper-3.6.2.jar:?]
        at CrowdControl-Paper-3.6.2.jar/dev.qixils.crowdcontrol.common.command.AbstractCommandRegister.initAll(AbstractCommandRegister.java:85) ~[CrowdControl-Paper-3.6.2.jar:?]
        at CrowdControl-Paper-3.6.2.jar/dev.qixils.crowdcontrol.plugin.paper.CommandRegister.createCommands(CommandRegister.java:33) ~[CrowdControl-Paper-3.6.2.jar:?]
        at CrowdControl-Paper-3.6.2.jar/dev.qixils.crowdcontrol.common.command.AbstractCommandRegister.getCommands(AbstractCommandRegister.java:120) ~[CrowdControl-Paper-3.6.2.jar:?]
        at CrowdControl-Paper-3.6.2.jar/dev.qixils.crowdcontrol.common.command.AbstractCommandRegister.register(AbstractCommandRegister.java:154) ~[CrowdControl-Paper-3.6.2.jar:?]
        at CrowdControl-Paper-3.6.2.jar/dev.qixils.crowdcontrol.plugin.paper.PaperCrowdControlPlugin.initCrowdControl(PaperCrowdControlPlugin.java:232) ~[CrowdControl-Paper-3.6.2.jar:?]
        at CrowdControl-Paper-3.6.2.jar/dev.qixils.crowdcontrol.plugin.paper.PaperCrowdControlPlugin.onEnable(PaperCrowdControlPlugin.java:263) ~[CrowdControl-Paper-3.6.2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[folia-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[folia-1.21.4.jar:1.21.4-DEV-d4bc338]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[folia-1.21.4.jar:1.21.4-DEV-d4bc338]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[folia-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:655) ~[folia-1.21.4.jar:1.21.4-DEV-d4bc338]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:604) ~[folia-1.21.4.jar:1.21.4-DEV-d4bc338]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:811) ~[folia-1.21.4.jar:1.21.4-DEV-d4bc338]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:558) ~[folia-1.21.4.jar:1.21.4-DEV-d4bc338]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:326) ~[folia-1.21.4.jar:1.21.4-DEV-d4bc338]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1318) ~[folia-1.21.4.jar:1.21.4-DEV-d4bc338]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:384) ~[folia-1.21.4.jar:1.21.4-DEV-d4bc338]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[13:57:30 INFO]: [CrowdControl] Disabling CrowdControl v3.6.2+paper
```

**Comment by qixils** [comment]
Hiya, 1.21.3+ support is already in the works and will be released with the v4 major mod rework

**Comment by Tudorhc5** [comment]
> Hiya, 1.21.3+ support is already in the works and will be released with the v4 major mod rework

Hello!

Sorry to bother, do you have any ETA on this? It would be highly appreciated <3

Have a lovely day!

**Comment by qixils** [comment]
The update is expected to release this month
